language: generic
sudo: required
services: 
  - docker

before_install: 
  - docker build -f Dockerfile.dev -t iliuhinmihai/docker-react . 


script:
  - docker run -e CI=true iliuhinmihai/docker-react npm run test